-- complain if script is sourced in psql, rather than via CREATE EXTENSION
\echo Use "CREATE EXTENSION idn" to load this file. \quit

CREATE OR REPLACE FUNCTION idn_utf8_nfkc_normalize(TEXT) returns TEXT LANGUAGE C IMMUTABLE STRICT as 'MODULE_PATHNAME';

CREATE OR REPLACE FUNCTION stringprep(TEXT, TEXT, TEXT DEFAULT NULL) returns TEXT LANGUAGE C IMMUTABLE as 'MODULE_PATHNAME', 'libidn_stringprep';
CREATE OR REPLACE FUNCTION idn_idna_decode(TEXT, TEXT DEFAULT NULL) returns TEXT LANGUAGE C IMMUTABLE as 'MODULE_PATHNAME';
CREATE OR REPLACE FUNCTION idn_idna_encode(TEXT, TEXT DEFAULT NULL) returns TEXT LANGUAGE C IMMUTABLE as 'MODULE_PATHNAME';

CREATE OR REPLACE FUNCTION idn_pr29_check(TEXT) returns bool LANGUAGE C IMMUTABLE STRICT as 'MODULE_PATHNAME';
CREATE OR REPLACE FUNCTION idn_punycode_encode(TEXT) returns TEXT LANGUAGE C STRICT IMMUTABLE as 'MODULE_PATHNAME';
CREATE OR REPLACE FUNCTION idn_punycode_decode(TEXT) returns TEXT LANGUAGE C STRICT IMMUTABLE as 'MODULE_PATHNAME';

CREATE OR REPLACE FUNCTION idn2_lookup(TEXT, TEXT DEFAULT NULL) returns TEXT LANGUAGE C IMMUTABLE as 'MODULE_PATHNAME', 'libidn2_lookup';
CREATE OR REPLACE FUNCTION idn2_register(TEXT, TEXT DEFAULT NULL, TEXT DEFAULT NULL) returns TEXT LANGUAGE C IMMUTABLE as 'MODULE_PATHNAME', 'libidn2_register';

CREATE OR REPLACE FUNCTION idn_constants() RETURNS TABLE(name TEXT, value INTEGER, description TEXT) LANGUAGE C IMMUTABLE AS 'MODULE_PATHNAME';
